### ISSUE TITLE
Red Hat DM and optaplanner

### ISSUE THREAD

**Issue by sarojshandilya** [jbossdemocentral/rhdm7-loan-demo-repo#1]
First of all i am not raising issue. I have some query.

This loan demo i understood and deploy, here rule engine returns Yes/No about loan approval.

 Can Red Hat DM be used to book meeting room or book bed in hospital.

Booking bed hospital: DM should return bed nos(1 or many beds) which matches patient criteria.

For example there are 10 available beds in hospital 6 Male 4 Female, for Male patient DM should return all 6 bed info back to calling application.

And the rule engine should be able to fetch available bed from database.

I have done with optaplanner and it working  well but how to do in DM , client do not want optaplanner

Regards
Saroj

**Comment by DuncanDoyle** [comment]
OptaPlanner (or Business Optimizer as the product is called) is part of the Red Hat Decision Manager offering. So, OptaPlanner is included in DM.

Wrt to whether you can do the task described with DM (I think you're referring to the Drools part of DM), without OptaPlanner, the answer is "no". These kind of problems are optimization problems, which require specific AI heuristic algorithms to be optimized. This is exactly the functionality OptaPlanner provides.
